// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: calculator_message.proto

package emergency_funds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateEmergencyFundsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonthlyIncome             string        `protobuf:"bytes,1,opt,name=monthly_income,json=monthlyIncome,proto3" json:"monthly_income,omitempty"`
	MonthlyExpense            string        `protobuf:"bytes,2,opt,name=monthly_expense,json=monthlyExpense,proto3" json:"monthly_expense,omitempty"`
	FinancialResponsibilities string        `protobuf:"bytes,3,opt,name=financial_responsibilities,json=financialResponsibilities,proto3" json:"financial_responsibilities,omitempty"`
	MaritalStatus             MaritalStatus `protobuf:"varint,4,opt,name=marital_status,json=maritalStatus,proto3,enum=MaritalStatus" json:"marital_status,omitempty"`
	NumberOfChildren          uint32        `protobuf:"varint,5,opt,name=number_of_children,json=numberOfChildren,proto3" json:"number_of_children,omitempty"`
}

func (x *CalculateEmergencyFundsRequest) Reset() {
	*x = CalculateEmergencyFundsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateEmergencyFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateEmergencyFundsRequest) ProtoMessage() {}

func (x *CalculateEmergencyFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateEmergencyFundsRequest.ProtoReflect.Descriptor instead.
func (*CalculateEmergencyFundsRequest) Descriptor() ([]byte, []int) {
	return file_calculator_message_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateEmergencyFundsRequest) GetMonthlyIncome() string {
	if x != nil {
		return x.MonthlyIncome
	}
	return ""
}

func (x *CalculateEmergencyFundsRequest) GetMonthlyExpense() string {
	if x != nil {
		return x.MonthlyExpense
	}
	return ""
}

func (x *CalculateEmergencyFundsRequest) GetFinancialResponsibilities() string {
	if x != nil {
		return x.FinancialResponsibilities
	}
	return ""
}

func (x *CalculateEmergencyFundsRequest) GetMaritalStatus() MaritalStatus {
	if x != nil {
		return x.MaritalStatus
	}
	return MaritalStatus_MARITAL_STATUS_UNSPECIFIED
}

func (x *CalculateEmergencyFundsRequest) GetNumberOfChildren() uint32 {
	if x != nil {
		return x.NumberOfChildren
	}
	return 0
}

type CalculateEmergencyFundsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecommendedFunds string        `protobuf:"bytes,1,opt,name=recommended_funds,json=recommendedFunds,proto3" json:"recommended_funds,omitempty"`
	MaritalStatus    MaritalStatus `protobuf:"varint,2,opt,name=marital_status,json=maritalStatus,proto3,enum=MaritalStatus" json:"marital_status,omitempty"`
}

func (x *CalculateEmergencyFundsResponse) Reset() {
	*x = CalculateEmergencyFundsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calculator_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateEmergencyFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateEmergencyFundsResponse) ProtoMessage() {}

func (x *CalculateEmergencyFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateEmergencyFundsResponse.ProtoReflect.Descriptor instead.
func (*CalculateEmergencyFundsResponse) Descriptor() ([]byte, []int) {
	return file_calculator_message_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateEmergencyFundsResponse) GetRecommendedFunds() string {
	if x != nil {
		return x.RecommendedFunds
	}
	return ""
}

func (x *CalculateEmergencyFundsResponse) GetMaritalStatus() MaritalStatus {
	if x != nil {
		return x.MaritalStatus
	}
	return MaritalStatus_MARITAL_STATUS_UNSPECIFIED
}

var File_calculator_message_proto protoreflect.FileDescriptor

var file_calculator_message_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x65, 0x6e, 0x75, 0x6d,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x02, 0x0a, 0x1e, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x46, 0x75,
	0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x6f,
	0x6e, 0x74, 0x68, 0x6c, 0x79, 0x5f, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x49, 0x6e, 0x63, 0x6f, 0x6d,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x6c, 0x79, 0x5f, 0x65, 0x78, 0x70,
	0x65, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x6f, 0x6e, 0x74,
	0x68, 0x6c, 0x79, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x1a, 0x66, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x69,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x19,
	0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0e, 0x6d, 0x61, 0x72,
	0x69, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x4d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0d, 0x6d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22, 0x85,
	0x01, 0x0a, 0x1f, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x65, 0x72,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65,
	0x64, 0x5f, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x46, 0x75, 0x6e, 0x64, 0x73, 0x12,
	0x35, 0x0a, 0x0e, 0x6d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x4d, 0x61, 0x72, 0x69, 0x74, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d, 0x6d, 0x61, 0x72, 0x69, 0x74, 0x61, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x65,
	0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2d, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calculator_message_proto_rawDescOnce sync.Once
	file_calculator_message_proto_rawDescData = file_calculator_message_proto_rawDesc
)

func file_calculator_message_proto_rawDescGZIP() []byte {
	file_calculator_message_proto_rawDescOnce.Do(func() {
		file_calculator_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_calculator_message_proto_rawDescData)
	})
	return file_calculator_message_proto_rawDescData
}

var file_calculator_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculator_message_proto_goTypes = []interface{}{
	(*CalculateEmergencyFundsRequest)(nil),  // 0: CalculateEmergencyFundsRequest
	(*CalculateEmergencyFundsResponse)(nil), // 1: CalculateEmergencyFundsResponse
	(MaritalStatus)(0),                      // 2: MaritalStatus
}
var file_calculator_message_proto_depIdxs = []int32{
	2, // 0: CalculateEmergencyFundsRequest.marital_status:type_name -> MaritalStatus
	2, // 1: CalculateEmergencyFundsResponse.marital_status:type_name -> MaritalStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_calculator_message_proto_init() }
func file_calculator_message_proto_init() {
	if File_calculator_message_proto != nil {
		return
	}
	file_enums_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_calculator_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateEmergencyFundsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calculator_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateEmergencyFundsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calculator_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_calculator_message_proto_goTypes,
		DependencyIndexes: file_calculator_message_proto_depIdxs,
		MessageInfos:      file_calculator_message_proto_msgTypes,
	}.Build()
	File_calculator_message_proto = out.File
	file_calculator_message_proto_rawDesc = nil
	file_calculator_message_proto_goTypes = nil
	file_calculator_message_proto_depIdxs = nil
}
