// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AppValidator is an autogenerated mock type for the AppValidator type
type AppValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: objWithStructTag
func (_m *AppValidator) Validate(objWithStructTag interface{}) error {
	ret := _m.Called(objWithStructTag)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(objWithStructTag)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAppValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewAppValidator creates a new instance of AppValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAppValidator(t mockConstructorTestingTNewAppValidator) *AppValidator {
	mock := &AppValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
