// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/assignment-go-rest-api/pb"
)

// EmergencyFundsServiceClient is an autogenerated mock type for the EmergencyFundsServiceClient type
type EmergencyFundsServiceClient struct {
	mock.Mock
}

// CalculateEmergencyFunds provides a mock function with given fields: ctx, in, opts
func (_m *EmergencyFundsServiceClient) CalculateEmergencyFunds(ctx context.Context, in *pb.EmergencyFundsReq, opts ...grpc.CallOption) (*pb.EmergencyFundsRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.EmergencyFundsRes
	if rf, ok := ret.Get(0).(func(context.Context, *pb.EmergencyFundsReq, ...grpc.CallOption) *pb.EmergencyFundsRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.EmergencyFundsRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.EmergencyFundsReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewEmergencyFundsServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewEmergencyFundsServiceClient creates a new instance of EmergencyFundsServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEmergencyFundsServiceClient(t mockConstructorTestingTNewEmergencyFundsServiceClient) *EmergencyFundsServiceClient {
	mock := &EmergencyFundsServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
