// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/assignment-go-rest-api/pb"
)

// ResetPasswordServiceClient is an autogenerated mock type for the ResetPasswordServiceClient type
type ResetPasswordServiceClient struct {
	mock.Mock
}

// ApplyPassReset provides a mock function with given fields: ctx, in, opts
func (_m *ResetPasswordServiceClient) ApplyPassReset(ctx context.Context, in *pb.ApplyResetPassReq, opts ...grpc.CallOption) (*pb.ApplyResetPassRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.ApplyResetPassRes
	if rf, ok := ret.Get(0).(func(context.Context, *pb.ApplyResetPassReq, ...grpc.CallOption) *pb.ApplyResetPassRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ApplyResetPassRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.ApplyResetPassReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestPassReset provides a mock function with given fields: ctx, in, opts
func (_m *ResetPasswordServiceClient) RequestPassReset(ctx context.Context, in *pb.RequestResetPassReq, opts ...grpc.CallOption) (*pb.RequestResetPassRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.RequestResetPassRes
	if rf, ok := ret.Get(0).(func(context.Context, *pb.RequestResetPassReq, ...grpc.CallOption) *pb.RequestResetPassRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.RequestResetPassRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.RequestResetPassReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewResetPasswordServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewResetPasswordServiceClient creates a new instance of ResetPasswordServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewResetPasswordServiceClient(t mockConstructorTestingTNewResetPasswordServiceClient) *ResetPasswordServiceClient {
	mock := &ResetPasswordServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
