// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/assignment-go-rest-api/pb"
)

// TransactionServiceClient is an autogenerated mock type for the TransactionServiceClient type
type TransactionServiceClient struct {
	mock.Mock
}

// GetAllTransactions provides a mock function with given fields: ctx, in, opts
func (_m *TransactionServiceClient) GetAllTransactions(ctx context.Context, in *pb.TransactionsReq, opts ...grpc.CallOption) (*pb.TransactionPaginationRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.TransactionPaginationRes
	if rf, ok := ret.Get(0).(func(context.Context, *pb.TransactionsReq, ...grpc.CallOption) *pb.TransactionPaginationRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransactionPaginationRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.TransactionsReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUp provides a mock function with given fields: ctx, in, opts
func (_m *TransactionServiceClient) TopUp(ctx context.Context, in *pb.TopUpReq, opts ...grpc.CallOption) (*pb.TransactionRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.TransactionRes
	if rf, ok := ret.Get(0).(func(context.Context, *pb.TopUpReq, ...grpc.CallOption) *pb.TransactionRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransactionRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.TopUpReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transfer provides a mock function with given fields: ctx, in, opts
func (_m *TransactionServiceClient) Transfer(ctx context.Context, in *pb.TransferReq, opts ...grpc.CallOption) (*pb.TransactionRes, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *pb.TransactionRes
	if rf, ok := ret.Get(0).(func(context.Context, *pb.TransferReq, ...grpc.CallOption) *pb.TransactionRes); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.TransactionRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *pb.TransferReq, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionServiceClient creates a new instance of TransactionServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionServiceClient(t mockConstructorTestingTNewTransactionServiceClient) *TransactionServiceClient {
	mock := &TransactionServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
