// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTransactionServiceServer is an autogenerated mock type for the UnsafeTransactionServiceServer type
type UnsafeTransactionServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTransactionServiceServer provides a mock function with given fields:
func (_m *UnsafeTransactionServiceServer) mustEmbedUnimplementedTransactionServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeTransactionServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeTransactionServiceServer creates a new instance of UnsafeTransactionServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeTransactionServiceServer(t mockConstructorTestingTNewUnsafeTransactionServiceServer) *UnsafeTransactionServiceServer {
	mock := &UnsafeTransactionServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
