// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeResetPasswordServiceServer is an autogenerated mock type for the UnsafeResetPasswordServiceServer type
type UnsafeResetPasswordServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedResetPasswordServiceServer provides a mock function with given fields:
func (_m *UnsafeResetPasswordServiceServer) mustEmbedUnimplementedResetPasswordServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeResetPasswordServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeResetPasswordServiceServer creates a new instance of UnsafeResetPasswordServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeResetPasswordServiceServer(t mockConstructorTestingTNewUnsafeResetPasswordServiceServer) *UnsafeResetPasswordServiceServer {
	mock := &UnsafeResetPasswordServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
