// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAuthServiceServer is an autogenerated mock type for the UnsafeAuthServiceServer type
type UnsafeAuthServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedAuthServiceServer provides a mock function with given fields:
func (_m *UnsafeAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeAuthServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeAuthServiceServer creates a new instance of UnsafeAuthServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeAuthServiceServer(t mockConstructorTestingTNewUnsafeAuthServiceServer) *UnsafeAuthServiceServer {
	mock := &UnsafeAuthServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
