// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeEmergencyFundsServiceServer is an autogenerated mock type for the UnsafeEmergencyFundsServiceServer type
type UnsafeEmergencyFundsServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedEmergencyFundsServiceServer provides a mock function with given fields:
func (_m *UnsafeEmergencyFundsServiceServer) mustEmbedUnimplementedEmergencyFundsServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeEmergencyFundsServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeEmergencyFundsServiceServer creates a new instance of UnsafeEmergencyFundsServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeEmergencyFundsServiceServer(t mockConstructorTestingTNewUnsafeEmergencyFundsServiceServer) *UnsafeEmergencyFundsServiceServer {
	mock := &UnsafeEmergencyFundsServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
