// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeGameServiceServer is an autogenerated mock type for the UnsafeGameServiceServer type
type UnsafeGameServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGameServiceServer provides a mock function with given fields:
func (_m *UnsafeGameServiceServer) mustEmbedUnimplementedGameServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeGameServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeGameServiceServer creates a new instance of UnsafeGameServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeGameServiceServer(t mockConstructorTestingTNewUnsafeGameServiceServer) *UnsafeGameServiceServer {
	mock := &UnsafeGameServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
