// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeCalculatorServiceServer is an autogenerated mock type for the UnsafeCalculatorServiceServer type
type UnsafeCalculatorServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedCalculatorServiceServer provides a mock function with given fields:
func (_m *UnsafeCalculatorServiceServer) mustEmbedUnimplementedCalculatorServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeCalculatorServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeCalculatorServiceServer creates a new instance of UnsafeCalculatorServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeCalculatorServiceServer(t mockConstructorTestingTNewUnsafeCalculatorServiceServer) *UnsafeCalculatorServiceServer {
	mock := &UnsafeCalculatorServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
